### PR TITLE
Designed inventory form

### PR DESCRIPTION
**Pull request by heinctz**
I finished designing the inventory form let met know what you guys think

### CODE REVIEW

**Comment by Reddanger19** [comment]
nice

**Comment by janro13806** [comment]
lyk crap, vrander als

**Comment by heinctz** [comment]
@Reddanger19 thanks for the nice

**Comment by Reddanger19** [comment]
> lyk crap, vrander als

nee man

**Comment by RainierIT** [comment]
baie kak

**Comment by Reddanger19** [comment]
> baie kak

jou ma man

**Comment by RainierIT** [comment]
,

**Comment by janro13806** [comment]
looks better

**Comment by heinctz** [comment]
yes dit lyk nie meer kak nie. Wat dink julle?

**Comment by Reddanger19** [comment]
better

**Pull request merged**
